# Numpy

Numpy adalah library yang digunakan untuk komputasi matematika saintifik

In [ ]:
# pip install numpy

In [2]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5]) # array dalam numpy
print(a)

[1 2 3 4 5]


In [4]:
b = [1,2,3,4,5] # list dalam python
print(b)

[1, 2, 3, 4, 5]


In [5]:
a = a+1
print(a)

[2 3 4 5 6]


In [8]:
a = a-1
print(a)

[0 1 2 3 4]


In [6]:
b = b+1 
print(b)

TypeError: can only concatenate list (not "int") to list

In [9]:
# Vector numpy dengan angka yang berkoma 
c = np.array([1, 1.5, 2, 3.6, 5]) 
print(c)

[1.  1.5 2.  3.6 5. ]


In [10]:
c1 = [1, 1.5, 2, 3.6, 5]
print(c1)

[1, 1.5, 2, 3.6, 5]


In [11]:
# vector dengan range
d = np.arange(1, 10, 1)
print(d)

[1 2 3 4 5 6 7 8 9]


In [12]:
# vector dengan range
d = np.arange(3, 10, 2)
print(d)

[3 5 7 9]


In [13]:
# vector dengan linear space
e = np.linspace(1, 10, 2)
print(e)

[ 1. 10.]


In [15]:
# vector dengan linear space
e = np.linspace(1, 10, 4)
print(e)

[ 1.  4.  7. 10.]


In [16]:
# array multi dimensi -> matriks
f = np.array([(1,2,3), (4,5,6)]) # array dalam numpy
print(f)

[[1 2 3]
 [4 5 6]]


In [17]:
print(f+1)

[[2 3 4]
 [5 6 7]]


In [18]:
print(f-1)

[[0 1 2]
 [3 4 5]]


In [19]:
print(f*2)

[[ 2  4  6]
 [ 8 10 12]]


In [20]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [22]:
a = np.zeros((5,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [24]:
a = np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# matriks Identitas cara 1
a= np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
# matriks Identitas cara 2
a= np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
# Operasi Aritmatika dalam numpy

# list dalam python
a = [1,2,3,4,5]
b = [6,7,8,9,10]

#array dalam numpy
anp= np.array([1,2,3,4,5])
bnp= np.array([6,7,8,9,10])

In [28]:
# Penjumlahan
hasil = a + b
print(hasil)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [29]:
hasil = anp + bnp
print(hasil)

[ 7  9 11 13 15]


In [30]:
# Pengurangan
hasil = anp - bnp
print(hasil)

[-5 -5 -5 -5 -5]


In [31]:
# perkalian
hasil = anp * bnp
print(hasil)

[ 6 14 24 36 50]


In [32]:
# pembagian
hasil = anp / bnp
print(hasil)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [33]:
# perpangkatan 
hasilanp = anp ** 2
hasilbnp = bnp ** 2
print(hasilanp)
print(hasilbnp)

[ 1  4  9 16 25]
[ 36  49  64  81 100]


In [35]:
# operasi aritmatika dalam array multidimensi
c = np.array([(1,2,3), (4,5,6)])
d = np.array([(-1,-2,-3), (7,8,9)])

In [36]:
print(c + d)

[[ 0  0  0]
 [11 13 15]]


In [38]:
print(c - d)

[[ 2  4  6]
 [-3 -3 -3]]


In [37]:
print(c * d)

[[-1 -4 -9]
 [28 40 54]]


In [39]:
print(c / d)

[[-1.         -1.         -1.        ]
 [ 0.57142857  0.625       0.66666667]]


In [40]:
# indexing , slicing, iteration
a = np.arange(10)**2
print (a)

[ 0  1  4  9 16 25 36 49 64 81]


In [42]:
# indexing = mengambil elemen tertentu dalam vektor
print("Cetak elemen pertama", a[5])

Cetak elemen pertama 25


In [47]:
# Slicing : memotong elemen tertentu 
print ("Cetak elemen pertama sampai kelima ", a[:5])

Cetak elemen pertama sampai kelima  [ 0  1  4  9 16]


In [ ]:
print("Cetak elemen kelima sampai terakhir ", a[4:9])

Cetak elemen kelima sampai terakhir  [16 25 36 49 64 81]


In [48]:
print("Cetak elemen kedua sampai kelima ", a[1:5])

Cetak elemen kedua sampai kelima  [ 1  4  9 16]


In [49]:
# iteration 
for i in a :
    print(i)

0
1
4
9
16
25
36
49
64
81


In [50]:
# Perkalian matriks 
a = np.array([(1,2), (3,4)])
print("Matriks a :")
print(a)

Matriks a :
[[1 2]
 [3 4]]


In [51]:
# Perkalian matriks 
b = np.ones((2,2))
print("Matriks b :")
print(b)

Matriks b :
[[1. 1.]
 [1. 1.]]


In [52]:
# operasi element wise
print(a*b)

[[1. 2.]
 [3. 4.]]


In [53]:
# cara pertama 
c1 = np.dot(a,b)
print (c1)

[[3. 3.]
 [7. 7.]]


In [54]:
c2 = a.dot(b)
print (c2)

[[3. 3.]
 [7. 7.]]


In [ ]:
# manipulation matriks
# transpose
# Vector baris
# Reshape

In [55]:
a = np.array([(1,2,3), (4,5,6)])

In [56]:
print("Matriks a ukurannya", a.shape)
print(a)

Matriks a ukurannya (2, 3)
[[1 2 3]
 [4 5 6]]


In [57]:
# transpose 
c1 = a.transpose()
c2 = np.transpose(a)
c3 = a.T
print(c1)
print(c2)
print(c3)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [58]:
# Matrix menjadi vector baris / flatter array
vb = np.ravel(a)
print(vb)

[1 2 3 4 5 6]


In [59]:
# Reshape
a= a.reshape(3,2)
print(a)
print("Matriks a ukurannya", a.shape)

[[1 2]
 [3 4]
 [5 6]]
Matriks a ukurannya (3, 2)


In [62]:
a = np.array([(1,2,3), (4,5,6), (4,5,6),(4,5,6)])
print("Matriks a ukurannya", a.shape)
print(a)

Matriks a ukurannya (4, 3)
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [63]:
a= a.reshape(6,2)
print(a)
print("Matriks a ukurannya", a.shape)

[[1 2]
 [3 4]
 [5 6]
 [4 5]
 [6 4]
 [5 6]]
Matriks a ukurannya (6, 2)
